version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: gaz
      POSTGRES_USER: gaz
      POSTGRES_PASSWORD: gazpass
    volumes:
      - gaz-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      backend:
        aliases:
          - db

  app:
    image: gitea.cosmin-lab.cloud/cosmin/calculatorgaz:latest
    environment:
      DATABASE_URL: postgresql://gaz:gazpass@db:5432/gaz
      HOSTNAME: 0.0.0.0
      RESET_PASSWORD_BASE_URL: https://reset.gaz.cosmin-lab.cloud/
      DISCORD_RESET_WEBHOOK_URL: https://discord.com/api/webhooks/1417184822111113326/f3ah4RcK7YNEFZ5LD_uBdVuOtEWNDhufgzSXXv9fkPeCBMTQjr8KMeGRsya1_XFbjTpd
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
    networks:
      backend:
        aliases:
          - app
      frontend:
        aliases:
          - app

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      frontend:
        aliases:
          - nginx

volumes:
  gaz-db-data:

networks:
  frontend:
  backend:
