apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculatorgaz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://10.13.13.101:8085/cosmin/gaz.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: gaz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
