apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculatorgaz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://forgejo.forgejo.svc.cluster.local:3000/cosmin/gaz-gitops.git
    targetRevision: main
    path: k8s/chart
    helm:
      releaseName: gaz
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gaz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
